name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.Workflows }}
      with:
        source_file: 'copy_me.txt'
        destination_repo: 'DavidOry/complete-streets'
        destination_folder: 'data'
        user_email: 'david.ory@gmail.com'
        user_name: 'DavidOry'
